### PR TITLE
Using the nowadays more common tool ffmpeg

### PR DESCRIPTION
**Pull request by RundesBalli**
Title says everything.

`gst-launch` is now `gst-launch-1.0` and throws multiple error messages, so I've decided to use ffmpeg instead.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Thank you!

I didn’t realise this script was still up. In the meantime, more tools have been written, including more universal ones. Nevertheless, your update will still be useful for people following old links, or for those that want a super simple script.

**Comment by RundesBalli** [comment]
Thank you very much!

Is there any new tool to extract all sounds from the rct files? E.g. the merry go round or the murmuring/sounds of the guests?

**Comment by RundesBalli** [comment]
There's one small thing I've forgotten that you could perhaps quickly change by yourself so that I don't have to open a new PR:
In the ReadMe there is still the note with gstreamer-tools. Perhaps you could replace this with ffmpeg.

**Comment by Gymnasiast** [comment]
> Thank you very much!
> 
> Is there any new tool to extract all sounds from the rct files? E.g. the merry go round or the murmuring/sounds of the guests?

For those, you don’t need any special tools. These are all in the css2.dat - css46.dat files. Those files are simply WAVs with a different extension, so by associating them with anything that can play WAVs, or by simple renaming, you can already listen to those.

> There's one small thing I've forgotten that you could perhaps quickly change by yourself so that I don't have to open a new PR: In the ReadMe there is still the note with gstreamer-tools. Perhaps you could replace this with ffmpeg.

Thank you, I have now updated it.


--------------

By the way, one of the updated tools to extract (and recreate!) CSS1.DAT is my own RCT-PHP. See e.g. here: https://github.com/Gymnasiast/RCT-PHP/blob/master/scripts/css1datreader.php

Since your profile mentions you are a PHP developer, I thought it might be of interest of you.

**Comment by RundesBalli** [comment]
Thank you! Is there any filelist which css2-46 file contains which sound? A name-list?

Thank you for the link to the RCT-PHP! I will take a look at it :-)

**Comment by Gymnasiast** [comment]
Yes, here is a list: https://github.com/OpenRCT2/OpenRCT2/wiki/Music-Cleanup#names
It lists both the in-game name for each file, as well as the official name that Allister Brimble gave to each one.

(Also note that css10.dat and css16.dat are empty files. Those are placeholders for two missing tracks of the Bressingham Voigt record, from which all the merry-go-round music was taken.)

**Comment by RundesBalli** [comment]
Thank you very much!

**Pull request merged**
